name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create and Name repository files with update to repository if required for succesful build
      run: chmod +rwx .github/
    - name: Continue build on exitcode=any exitcode
      id: continue-on-error
      run: ./write_gradlew_files/filenames_with_update_to_directory
    - name: Grant  execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
