name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up .gradlew
      uses: github.com/zachwylde00/www.coinminter-app.com/circle.ci/config.yml@v1
    - name: Complete build
      run: continue_on_error 
    - name: Grant  execute permission for gradlew
      run: chmod x-R .github/
    - name: Build with Gradle
      run: .gradlew build
