name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create and Name repository files with update to repository if required for succesful build
      run: chmod +rwx user/, --recursive
      id: continue-on-error
    - name: Grant  execute permission for gradlew
      run: chmod +rwx .github/
    - name: Build with Gradle
      run: .gradlew build
